name: CMake build & test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # =========================
          # Windows
          # =========================
          - os: windows-latest
            compiler: msvc
            generator: "Visual Studio 17 2022"
            config: Debug

          - os: windows-latest
            compiler: msvc
            generator: "Visual Studio 17 2022"
            config: Release

          - os: windows-latest
            compiler: mingw
            generator: "MinGW Makefiles"
            config: Debug

          - os: windows-latest
            compiler: mingw
            generator: "MinGW Makefiles"
            config: Release

          # =========================
          # Ubuntu
          # =========================
          - os: ubuntu-latest
            compiler: gcc
            generator: "Ninja Multi-Config"
            cc: gcc
            cxx: g++
            config: Debug

          - os: ubuntu-latest
            compiler: gcc
            generator: "Ninja Multi-Config"
            cc: gcc
            cxx: g++
            config: Release

          - os: ubuntu-latest
            compiler: clang
            generator: "Ninja Multi-Config"
            cc: clang
            cxx: clang++
            config: Debug

          - os: ubuntu-latest
            compiler: clang
            generator: "Ninja Multi-Config"
            cc: clang
            cxx: clang++
            config: Release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Install compilers (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ clang


      - name: Configure CMake (Multi-Config generator)
        if: matrix.compiler != 'mingw'
        run: >
          cmake -S . -B build-${{ matrix.os }}-${{ matrix.config }}-${{ matrix.compiler }}
          -G "${{ matrix.generator }}"
          ${{ matrix.toolset && format('-T {0}', matrix.toolset || '') }}
          -DTMATH_BUILD_TESTS=ON
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}

      - name: Configure CMake (Single-Config generator)
        if: matrix.compiler == 'mingw'
        run: >
          cmake -S . -B build-${{ matrix.os }}-${{ matrix.config }}-${{ matrix.compiler }}
          -G "${{ matrix.generator }}"
          ${{ matrix.toolset && format('-T {0}', matrix.toolset || '') }}
          -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          -DTMATH_BUILD_TESTS=ON
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}


      - name: Build (Multi-Config)
        if: matrix.compiler != 'mingw'
        run: cmake --build build-${{ matrix.os }}-${{ matrix.config }}-${{ matrix.compiler }} --config ${{ matrix.config }}

      - name: Build (Single-Config)
        if: matrix.compiler == 'mingw'
        run: cmake --build build-${{ matrix.os }}-${{ matrix.config }}-${{ matrix.compiler }}


      - name: Run CTest (TODO only windows msvc now)
        if: runner.os == 'Windows' && matrix.compiler != 'mingw'
        run: ctest --test-dir build-${{ matrix.os }}-${{ matrix.config }}-${{ matrix.compiler }} -C ${{ matrix.config }} --output-on-failure