name: CMake build & test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        config: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      # 配置 CMake
      - name: Configure CMake
        run: cmake -S . -B build-${{ matrix.os }}-${{ matrix.config }} -DTMATH_BUILD_TESTS=ON

      # 编译
      - name: Build
        run: cmake --build build-${{ matrix.os }}-${{ matrix.config }} --config ${{ matrix.config }}

      # 运行测试
      - name: Run CTest
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ctest --test-dir build-${{ matrix.os }}-${{ matrix.config }} -C ${{ matrix.config }} --output-on-failure
          else
            ctest --test-dir build-${{ matrix.os }}-${{ matrix.config }} --output-on-failure
          fi